In [3]:
import numpy as np

dizi1 = np.array([1, 3, 5, 7, 9]) # dizi1 --orijinal dizi
dizi2 = dizi1.copy() # dizi2 --orijinal dizinin kopyası
dizi1[0] = 57        # orijinal diziyi değiştirelim

print(dizi1)
print(dizi2) # dizi2 de değişti mi?

[57  3  5  7  9]
[1 3 5 7 9]


In [4]:
import numpy as np

dizi1 = np.array([1, 3, 5, 7, 9]) # dizi1 --orijinal dizi
dizi2 = dizi1.view() # dizi2 -- orijinal dizinin görünümü
dizi1[0] = 57        # orijinal diziyi değiştirelim

print(dizi1)
print(dizi2) # dizi2 de değişti mi?

[57  3  5  7  9]
[57  3  5  7  9]


In [5]:
import numpy as np

dizi1 = np.array([1, 3, 5, 7, 9]) # dizi1 --orijinal dizi
dizi2 = dizi1.view()  # dizi2 -- orijinal dizinin görünümü
dizi2[0] = 57         # görünüm diziyi değiştirelim

print(dizi1) # dizi1 de değişti mi?
print(dizi2) 

[57  3  5  7  9]
[57  3  5  7  9]


In [6]:
# base ile veri kontrolü
import numpy as np

dizi = np.array([1, 3, 5, 7, 9])

adana = dizi.copy()
bursa = dizi.view()

print(adana.base)
print(bursa.base)

None
[1 3 5 7 9]


In [7]:
# bir dizinin shape'ini almak
import numpy as np

dizi = np.array([[1, 3, 5, 7, 9], [2, 4, 6, 8, 10]])

print(dizi.shape) # 2D bir dizinin shape'ini yazdıralım

(2, 5)


In [12]:
import numpy as np
dizi = np.array([1, 2, 3, 4], ndmin=3)

print(dizi)
print(dizi.shape)

[[[1 2 3 4]]]
(1, 1, 4)


In [13]:
# reshape 1-D den 2-D ye
import numpy as np

aylar = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

uc_aylar = aylar.reshape(4, 3)

print(uc_aylar)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [15]:
# reshape 1-D den 3-D ye
import numpy as np

dizi = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

yeni_dizi = dizi.reshape(2, 3, 2)

print(yeni_dizi)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [16]:
# reshape için gerekli elemanlar her iki şekilde de eşit olmalıdır
import numpy as np

dizi = np.array([1, 2, 3, 4, 5, 6, 7, 8])

yeni_dizi = dizi.reshape(3, 3)

print(yeni_dizi)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [17]:
# Reshape ile oluşturulan yeni dizi copy dizi mi olur view mi olur?
import numpy as np

dizi = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(dizi.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [18]:
# bilinmeyen boyut
# 8 elemanlı 1D dizisini 2x2 elemanlı 3D diziye dönüştürelim

import numpy as np

dizi= np.array([1, 2, 3, 4, 5, 6, 7, 8])

yeni_dizi = dizi.reshape(2, 2, -1) # -1 bilinmeyen boyut yerine

print(yeni_dizi)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [19]:
# flattening
# Çok boyutlu diziyi tek boyuta indirme
import numpy as np

dizi = np.array([[1, 3, 5, 7], [2, 4, 6, 8]])

yeni_dizi = dizi.reshape(-1)

print(yeni_dizi)

[1 3 5 7 2 4 6 8]
