In [8]:
#NumPy, geleneksel Python'un listelediğinden 
# 50 kat daha hızlı bir dizi nesnesi sağlamayı amaçlamaktadır.
import numpy as np

dizi = np.array(['A', 'B', 'C', 'D'])

print(dizi)

['A' 'B' 'C' 'D']


In [9]:
#NumPy'daki dizi nesnesine ndarray adı verilir
import numpy as np

dizi = np.array(['A', 'B', 'C', 'D'])

print(dizi)

print(type(dizi))

['A' 'B' 'C' 'D']
<class 'numpy.ndarray'>


In [10]:
#list, tuple, set, dict gibi dizi benzeri bir nesneyi ndarray yap
import numpy as np

tuple_dizi = np.array((34, 35, 57, 3))

print(tuple_dizi)

[34 35 57  3]


In [11]:
# 57 ile 0-D bir array oluşturalım
import numpy as np

dizi = np.array(57)

print(dizi)

57


In [12]:
# 1-D bir array oluşturalım
import numpy as np

cift_dizi = np.array([2, 4, 6, 8, 10])

print(cift_dizi)

[ 2  4  6  8 10]


In [13]:
# 2-D bir array oluşturalım
import numpy as np

dizi = np.array([[2,4,6,8,10],[1,3,5,7,9]])
# en dışa eklenen köşeli paranteze dikkat!

print(dizi)

[[ 2  4  6  8 10]
 [ 1  3  5  7  9]]


In [14]:
# 3-D bir array oluşturalım
import numpy as np

dizi3D = np.array([[[2,4,6,8,10],[1,3,5,7,9]], [[2,4,6,8,10],[1,3,5,7,9]]])

print(dizi3D)

[[[ 2  4  6  8 10]
  [ 1  3  5  7  9]]

 [[ 2  4  6  8 10]
  [ 1  3  5  7  9]]]


In [17]:
#ndim ile bir dizinin boyutunu öğrenme
import numpy as np

dizi0 = np.array(57)

dizi1 = np.array([2, 4, 6, 8, 10])

dizi2 = np.array([[1, 3, 5, 7, 9], [2, 4, 6, 8, 10]])

dizi3 = np.array([[[1, 3, 5, 7, 9], [2, 4, 6, 8, 10]], 
                  [[1, 3, 5, 7, 9], [2, 4, 6, 8, 10]]])

print(dizi0.ndim)
print(dizi1.ndim)
print(dizi2.ndim)
print(dizi3.ndim)

0
1
2
3


In [19]:
#ndmin değişkeni ile çok boyutlu dizi oluşturmak
import numpy as np

dizi = np.array([1, 3, 5, 7, 9], ndmin=6)

print(dizi)
print('Boyut sayısı:', dizi.ndim)

[[[[[[1 3 5 7 9]]]]]]
Boyut sayısı: 6


In [20]:
#dizi elelmanlarına erişim
import numpy as np

dizi = np.array([1, 3, 5, 7, 9])

print(dizi[0]) #dizinin ilk elemanı
print(dizi[1]) #dizinin 2. elemanı
print(dizi[4]) #dizinin 5. elemanı
print(dizi[1] * dizi[2]) #dizinin 2. ve 3. elemanının çarpımı

1
3
9
15


In [21]:
#2-D dizi elemanlarına erişim
import numpy as np

dizi = np.array([[1, 3, 5, 7, 9],[2, 4, 6, 8, 10]])

print(dizi[0,0]) #1. dizinin ilk elemanı
print(dizi[1,4]) #2. dizinin 5. elemanı
print(dizi[0,2]) #1. dizinin 3. elemanı
print(dizi[1,3] * dizi[0,2]) #2. dizinin 4. ve 1. dizinin 3. elemanının çarpımı

1
10
5
40


In [24]:
#3-D dizi elemanlarına erişim
import numpy as np

dizi = np.array([[[1, 3, 5, 7, 9], [2, 4, 6, 8, 10]], 
                 [[11, 13, 15, 17, 19], [12, 14, 16, 18,20]]])

print(dizi[0, 1, 2])

6


In [25]:
# Verilen dizideki 7, 8 ve 12 sayılarına erişmek için - şimdi siz yapın
import numpy as np

dizi = np.array([[[1, 3, 5, 7, 9], [2, 4, 6, 8, 10]], 
                 [[11, 13, 15, 17, 19], [12, 14, 16, 18,20]]])

print(dizi[0, 0, 3])
print(dizi[0, 1, 3])
print(dizi[1, 1, 0])

7
8
12


In [26]:
# negatif indeksleme
import numpy as np

dizi = np.array([[1, 3, 5, 7, 9],[2, 4, 6, 8, 10]])

print(dizi[0,-5]) #1. dizinin ilk elemanı
print(dizi[1,-1]) #2. dizinin 5. elemanı
print(dizi[0,-3]) #1. dizinin 3. elemanı

1
10
5


In [27]:
# negatif indeksleme- şimdi siz yapın
import numpy as np

dizi = np.array([[1, 3, 5, 7, 9],[2, 4, 6, 8, 10]])

print(dizi[0,-2]) #7
print(dizi[1,-2]) #8

7
8


In [28]:
# slicing
import numpy as np

dizi = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(dizi[0:5]) # dizideki elemanların ilk yarısını alalım 

[1 2 3 4 5]


In [30]:
# slicing - şimdi siz yapın
import numpy as np

dizi = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(dizi[5:10]) # dizideki elemanların diğer yarısını alalım 

[ 6  7  8  9 10]


In [32]:
 # 1-D diziler ile slicing
import numpy as np

dizi = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(dizi[5:]) #bitiş indeksi belirtilmezse
print(dizi[:5]) #başlangıç indeksi belirtilmezse
print(dizi[::2]) #ne başlangıç var ne bitiş
print(dizi[1::2]) #çift sayıları istiyorum
print(dizi[-2:]) #negatif indeksleme, bitiş yok
print(dizi[:-2]) #negatif indeksleme, başlangıç yok
print(dizi[-3:-2]) #negatif indeksleme
print(dizi[-3:2])
print(dizi[1:7:2]) #basamak belirtilirse

[ 6  7  8  9 10]
[1 2 3 4 5]
[1 3 5 7 9]
[ 2  4  6  8 10]
[ 9 10]
[1 2 3 4 5 6 7 8]
[8]
[]
[2 4 6]


In [33]:
# 2-D diziler ile slicing
import numpy as np

dizi = np.array([[1, 3, 5, 7, 9], [2, 4, 6, 8, 10]])

print(dizi[1, 1:4]) # unutmayın! dizinin ikinci elemanının indeksi 1
print(dizi[0:2, 2]) # her iki elemanın üçüncü elemanlarını al
print(dizi[0:2, 1:4]) # her iki elemanın 2.,3. ve 4. elemanlarını al, sonuç 2-D dizi 

[4 6 8]
[5 6]
[[3 5 7]
 [4 6 8]]
