In [27]:
#NumPy veri tipleri
import numpy as np
x = np.float32(155)
y = np.int_([10,112,40000])

print(x)
print(y)

155.0
[   10   112 40000]


In [36]:
#veri tipleri arasında dönüşüm
import numpy as np
x=np.array([1,2,3])

print(x.dtype) #x in veri tipi nedir

y=np.int8(x) #x in veri tipini değiştirelim

print(y.dtype) #yeni değer y nin veri tipi

int32
int8


In [12]:
import numpy as np

dizi1 = np.array([2.4, 3, 1.6, 0]) #list dizi nesnesini numpy dizisine dönüştürelim
print(dizi1) #çıktı-satır 1. numpy dizisini yazdıralım
print(dizi1.dtype) #çıktı-satır 2. numpy dizisinin veri tipi nedir?

#bir önceki dizinin veri tipini integer yapalım
#aşağıdaki komut satırında i yerine int de yazılabilir
dizi1_new = dizi1.astype('i') 
print(dizi1_new) #çıktı satır 3. yeni diziyi yazdıralım
print(dizi1_new.dtype) #çıktı satır 4. yeni dizinin veri tipini sorgulayalım.

#list, tuple ve çeşitli veri tiplerinden oluşan bir dizi tanımlayalım
dizi3 = np.array([[1,2.0],[0,0],(1+1j,3.)]) 
print(dizi3.dtype) #çıktı satır 5. bu dizinin veri tipi nedir?
print(dizi3) #çıktı satır 6. bu diziyi yazdıralım


[2.4 3.  1.6 0. ]
float64
[2 3 1 0]
int32
complex128
[[1.+0.j 2.+0.j]
 [0.+0.j 0.+0.j]
 [1.+1.j 3.+0.j]]


In [17]:
import numpy as np

#veri tipi string olan bir numpy dizisi oluşturalım
dizi0 = np.array([12, 200, 3500, 40000, 5], dtype='S')

print(dizi0)
print(dizi0.dtype)

[b'12' b'200' b'3500' b'40000' b'numpy']
|S5


In [16]:
import numpy as np

#veri tipi 4 byte integer olan bir numpy dizisi oluşturalım
dizi0 = np.array([12, 200, 3500, 40000, 5], dtype='i4')

print(dizi0)
print(dizi0.dtype)

[   12   200  3500 40000     5]
int32


In [19]:

import numpy as np

#dizi elemanları hem string hem sayısal değerler alıyorsa
#String veri tipine dönüştürülebilir 
#ancak sayısal veri tiplerine dönüştürülemez.
dizi0 = np.array([12, 200, 35, 4, 'numpy'], dtype='S')

print(dizi0) #çıktı satır 1- dizi elemanlarını yazdıralım
print(dizi0.dtype) #çıktı satır 2- dizi elemanlarının veri tipi nedir?
                  

[b'12' b'200' b'35' b'4' b'numpy']
|S5


In [21]:
import numpy as np
#'numpy' gibi bir string değer tamsayıya dönüştürülemez(hata oluşur)
dizi1 = np.array([12, 200, 35, 4, 'numpy'], dtype='int')

print(dizi1.dtype) # dizi elemanlarının veri tipi eşleşmiyor: ValueError

ValueError: invalid literal for int() with base 10: 'numpy'

In [22]:
#NumPy'da sıfırdan array oluşturmak
import numpy as np

#zeros belirtilen şekle sahip 0 değerlerle dolu bir dizi oluşturur
dizi= np.zeros((2, 3))

print(dizi)
print(dizi.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
float64


In [23]:
import numpy as np

#ones belirtilen şekle sahip 1 değerleriyle dolu bir dizi oluşturur
dizi= np.ones((2, 3))

print(dizi)
print(dizi.dtype)

[[1. 1. 1.]
 [1. 1. 1.]]
float64


In [24]:
import numpy as np
#arange düzenli olarak artan değerlere sahip diziler oluşturur. 
dizi1=np.arange(10) #başlangıç belirtilmezse 0'dan başlar

dizi2=np.arange(3, 12, dtype=float) #son değeri almadığına dikkat!

dizi3=np.arange(3, 5, 0.7) #3'ten 5'e kadar 0.7 artarak 

print(dizi1) #çıktı-satır 1
print(dizi2) #çıktı-satır 2
print(dizi3) #çıktı-satır 3

[0 1 2 3 4 5 6 7 8 9]
[ 3.  4.  5.  6.  7.  8.  9. 10. 11.]
[3.  3.7 4.4]


In [46]:
import numpy as np

z = np.linspace(3., 5., 5) 
# artım değerinin 5 girildiğine, çıktıda 0.5 olarak 
# algılandığına dikkat edin!
print(z)

[3.  3.5 4.  4.5 5. ]


In [37]:
import numpy as np

x = np.power(100, 8, dtype=np.int64)

y = np.power(100, 8, dtype=np.int32) #overflow error

print(x)
print(y)

10000000000000000
1874919424


In [38]:
import numpy as np
print(np.iinfo(int)) #kullandığım sistemdeki varsayılan int değerleri nedir?

print(np.iinfo(np.int32)) #32-bit integer sınırları nelerdir?
print(np.iinfo(np.int64)) #64-bit integer sınırları nelerdir?

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------



In [40]:
import numpy as np

print(np.power(100, 100, dtype=np.int64)) #çıktı için 64 bit integer yeterli değil-overflow 
print(np.power(100, 100, dtype=np.float64)) #float' a çevirelim 


0
1e+200
