In [1]:
# 1-D dizi üzerinde iterasyon
import numpy as np

dizi = np.array([1, 2, 3, 4, 5])

for eleman in dizi:
  print(eleman)

1
2
3
4
5


In [2]:
# 2-D dizi üzerinde iterasyon
import numpy as np

dizi = np.array([[1, 3, 5], [7, 9, 11]] )

for eleman in dizi:
  print(eleman)

[1 3 5]
[ 7  9 11]


In [3]:
# 2-D dizi içindeki scaler değerleri döndürmek
import numpy as np

dizi = np.array([[1, 3, 5], [7, 9, 11]] )

for eleman in dizi:      
  for deger in eleman:
    print(deger) 

1
3
5
7
9
11


In [4]:
# 3-D dizide scaler değerleri yazdırmak
import numpy as np

dizi = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in dizi:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [5]:
# 3-D array de nditer() kullanımı
import numpy as np

dizi = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for deger in np.nditer(dizi):
  print(deger)

1
2
3
4
5
6
7
8


In [8]:
# 3-D array de nditer() kullanımı
# 1 değer atlayarak
import numpy as np

dizi = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for deger in np.nditer(dizi[:, :, ::2]):
  print(deger)

1
3
5
7


In [9]:
# ndenumerate() kullanımı
import numpy as np

dizi1D = np.array([1, 2, 3]) # 1-D dizi
dizi2D = np.array([[4, 5], [6, 7]]) # 2-D dizi

for idx, x in np.ndenumerate(dizi1D):
  print(idx, x)

for idy, y in np.ndenumerate(dizi2D):
  print(idy, y)

(0,) 1
(1,) 2
(2,) 3
(0, 0) 4
(0, 1) 5
(1, 0) 6
(1, 1) 7


In [10]:
# join işlemi 1-D
import numpy as np

dizi1 = np.array([1, 2, 3]) # 1-D array

dizi2 = np.array([4, 5, 6]) # 1-D array

dizi = np.concatenate((dizi1, dizi2)) # 1-D array

print(dizi)

[1 2 3 4 5 6]


In [11]:
# join işlemi 2-D
import numpy as np

dizi1 = np.array([[1, 2], [3, 4]]) #2-D dizi

dizi2 = np.array([[5, 6], [7, 8]]) #2-D dizi

dizi = np.concatenate((dizi1, dizi2)) #2-D dizi

print(dizi)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [12]:
# join işlemi 2-D axis=1
import numpy as np

dizi1 = np.array([[1, 2], [3, 4]]) #2-D dizi

dizi2 = np.array([[5, 6], [7, 8]]) #2-D dizi

dizi = np.concatenate((dizi1, dizi2), axis=1) #2-D dizi

print(dizi)

[[1 2 5 6]
 [3 4 7 8]]


In [13]:
#stack 1-D array'lerde kullanımı
import numpy as np

dizi1 = np.array([1, 2, 3])
dizi2 = np.array([4, 5, 6])

dizi_3 = np.stack((dizi1, dizi2), axis=1)
dizi_4 = np.stack((dizi1, dizi2), axis=0)

print(dizi_3) #axis=1
print(dizi_4) #axis=0

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


In [14]:
#hstack, vstack, dstack ve 1-D array'ler
import numpy as np

dizi1 = np.array([1, 2, 3])
dizi2 = np.array([4, 5, 6])

dizi_3 = np.hstack((dizi1, dizi2))
dizi_4 = np.vstack((dizi1, dizi2))
dizi_5 = np.dstack((dizi1, dizi2))

print(dizi_3) # satırlar boyunca
print(dizi_4) # sütunlar boyunca
print(dizi_5) # derinlik/yükseklik boyunca

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


In [1]:
# splitting arrays 1-D
import numpy as np

dizi = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

yeni_dizi = np.array_split(dizi, 4) # 4 parçaya bölelim

print(yeni_dizi)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]


In [2]:
# splitting arrays 1-D
import numpy as np

dizi = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

yeni_dizi = np.array_split(dizi, 5) # 5 parçaya bölelim

print(yeni_dizi)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8]), array([ 9, 10]), array([11, 12])]


In [3]:
import numpy as np

dizi = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

yeni_dizi = np.split(dizi, 5) # 5 parçaya bölelim
 
print(yeni_dizi) # 12/5 tam bölünmediğinden split() hata verir

ValueError: array split does not result in an equal division

In [4]:
# splitting arrays 1-D
# dizi elemanlarını yazdırma
import numpy as np

dizi = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

yeni_dizi = np.array_split(dizi, 4) # 4 parçaya bölelim

print(yeni_dizi[0])
print(yeni_dizi[1])
print(yeni_dizi[2])
print(yeni_dizi[3])

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [5]:
# splitting arrays 2-D
# dizi elemanlarını yazdırma
import numpy as np

dizi = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

yeni_dizi = np.array_split(dizi, 4) # 4 parçaya bölelim

print(yeni_dizi[0])
print(yeni_dizi[1])
print(yeni_dizi[2])
print(yeni_dizi[3])

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]]
[[11 12]]


In [6]:
# splitting arrays 2-D
# dizi elemanlarını yazdırma
import numpy as np

dizi = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

yeni_dizi = np.array_split(dizi, 3) # 3 parçaya bölelim

print(yeni_dizi[0])
print(yeni_dizi[1])
print(yeni_dizi[2])

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


In [8]:
# splitting arrays 2-D
import numpy as np

dizi = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

yeni_dizi = np.array_split(dizi, 4) # 4 parçaya bölelim

print(yeni_dizi[0])
print(yeni_dizi[1])
print(yeni_dizi[2])
print(yeni_dizi[3])

[[1 2 3]]
[[4 5 6]]
[[7 8 9]]
[[10 11 12]]


In [10]:
# splitting arrays 2-D
import numpy as np

dizi = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

yeni_dizi = np.array_split(dizi, 3) # 3 parçaya bölelim

print(yeni_dizi[0])
print(yeni_dizi[1])
print(yeni_dizi[2])

[[1 2 3]
 [4 5 6]]
[[7 8 9]]
[[10 11 12]]


In [11]:
# splitting arrays 2-D
import numpy as np

dizi = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

yeni_dizi = np.array_split(dizi, 3, axis=1) # satır boyunca 3 parçaya bölelim

print(yeni_dizi[0])
print(yeni_dizi[1])
print(yeni_dizi[2])

[[ 1]
 [ 4]
 [ 7]
 [10]]
[[ 2]
 [ 5]
 [ 8]
 [11]]
[[ 3]
 [ 6]
 [ 9]
 [12]]


In [13]:
# splitting arrays 2-D
import numpy as np

dizi = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

yeni_dizi = np.hsplit(dizi, 3) # satır boyunca 3 parça, hsplit()

print(yeni_dizi[0])
print(yeni_dizi[1])
print(yeni_dizi[2])

[[ 1]
 [ 4]
 [ 7]
 [10]]
[[ 2]
 [ 5]
 [ 8]
 [11]]
[[ 3]
 [ 6]
 [ 9]
 [12]]


In [15]:
# splitting arrays 2-D
import numpy as np

dizi = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

yeni_dizi = np.vsplit(dizi, 2) # sütun boyunca 2 parça, vsplit()

print(yeni_dizi[0])
print(yeni_dizi[1])

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [20]:
# dizilerde search -- arama
import numpy as np

dizi = np.array([1, 2, 10, 4, 15, 6, 10, 8, 10, 1, 15])

nerede = np.where(dizi == 10) # 10 hangi indekslerde

print(nerede)

(array([2, 6, 8], dtype=int64),)


In [21]:
# dizilerde search -- arama
import numpy as np

dizi = np.array([1, 2, 10, 4, 15, 6, 10, 8, 10, 1, 15])

nerede = np.where(dizi%2 == 0) # çift sayılar hangi indekslerde

print(nerede)

(array([1, 2, 3, 5, 6, 7, 8], dtype=int64),)


In [23]:
# dizilerde search -- arama
import numpy as np

dizi = np.array([1, 2, 3, 4, 5, 7, 8, 9, 10])

nereye = np.searchsorted(dizi, 6) # 6 nereye eklenmeli

print(nereye)

5


In [24]:
# dizilerde search -- arama
import numpy as np

dizi = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) # 6 var

nereye = np.searchsorted(dizi, 6) # 6 nereye eklenmeli

print(nereye)

5


In [28]:
# dizilerde search -- arama
import numpy as np

dizi = np.array([1, 2, 5, 7, 9]) 

nereye = np.searchsorted(dizi, [3, 4, 6, 8, 10])

print(nereye)

[2 2 3 4 5]


In [29]:
# dizilerde sorting -- sıralama
import numpy as np

dizi = np.array([10, 15, 6, 4, 3, 12, 0, 1])

print(np.sort(dizi))

[ 0  1  3  4  6 10 12 15]


In [30]:
# dizilerde sorting -- sıralama
import numpy as np

dizi = np.array([[10, 15, 6, 4], [3, 12, 0, 1]]) # 2-D

print(np.sort(dizi))

[[ 4  6 10 15]
 [ 0  1  3 12]]


In [32]:
# dizilerde filtering -- filtreleme
import numpy as np

dizi = np.array([10, 15, 6, 4, 3, 12, 0, 1]) #10,15,12 yi alalım

i=[True, True, False, False, False, True, False, False]

print(dizi[i])

[10 15 12]


In [34]:
# dizilerde filtering -- filtreleme
import numpy as np

dizi = np.array([10, 15, 6, 4, 3, 12, 0, 1])

# Boş bir dizi oluşturalım
i = []

# orijinal dizideki her bir elemana bakalım
for deger in dizi:
  if deger >= 6: #deger 6 ve 6'dan büyükse True döndürür
    i.append(True) #filtreye ekleyelim
  else:
    i.append(False) #değilse False döndürür ve eklenmez

yeni_dizi = dizi[i]

print(np.sort(yeni_dizi))

[ 6 10 12 15]


In [35]:
#  dizilerde filtering -- filtreleme
import numpy as np

dizi = np.array([10, 15, 6, 4, 3, 12, 0, 1])

# koşulu bu şekilde de belirtebiliriz 
i = (dizi%2 == 1) # tek sayıları alalım

yeni_dizi = dizi[i]

print(yeni_dizi)

[15  3  1]
